name: Test e2e

on:
  push:
    branches: [ "main" ]
    paths:
      - '!README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - '!README.md'
  workflow_dispatch:

jobs:
  test_e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'ts/package.json'

      - name: Install ts dependencies
        run: cd ts && pnpm install

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
          cache-dependency-path: "go.sum"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build release binary
        run: make release

      - name: Test
        run: make -f go.mk test-e2ef

